/// Static reference data — 18 provinces of Burundi + their communes.
/// Used by the salon location step (province/commune dropdowns).
abstract class BurundiProvinces {
  static const List<String> provinces = [
    'Bujumbura Mairie',
    'Bujumbura Rural',
    'Bubanza',
    'Bururi',
    'Cankuzo',
    'Cibitoke',
    'Gitega',
    'Karuzi',
    'Kayanza',
    'Kirundo',
    'Makamba',
    'Muramvya',
    'Muyinga',
    'Mwaro',
    'Ngozi',
    'Rumonge',
    'Rutana',
    'Ruyigi',
  ];

  static const Map<String, List<String>> communes = {
    'Bujumbura Mairie': ['Mukaza', 'Ntahangwa', 'Muha'],
    'Bujumbura Rural': [
      'Isale',
      'Kabezi',
      'Kanyosha',
      'Mubimbi',
      'Mugongomanga',
      'Mukike',
      'Mutambu',
      'Mutimbuzi',
      'Nyabiraba',
    ],
    'Bubanza': ['Bubanza', 'Gihanga', 'Mpanda', 'Musigati', 'Rugazi'],
    'Bururi': ['Bururi', 'Matana', 'Mugamba', 'Rutovu', 'Songa', 'Vyanda'],
    'Cankuzo': ['Cankuzo', 'Cendajuru', 'Gisagara', 'Kigamba', 'Mishiha'],
    'Cibitoke': [
      'Bukinanyana',
      'Buganda',
      'Mabayi',
      'Mugina',
      'Murwi',
      'Rugombo',
    ],
    'Gitega': [
      'Bugendana',
      'Bukirasazi',
      'Buraza',
      'Giheta',
      'Gishubi',
      'Gitega',
      'Itaba',
      'Makebuko',
      'Mutaho',
      'Nyarusange',
      'Ryansoro',
    ],
    'Karuzi': [
      'Buhiga',
      'Bugenyuzi',
      'Gihogazi',
      'Gitaramuka',
      'Mutumba',
      'Nyabikere',
      'Shombo',
    ],
    'Kayanza': [
      'Butaganzwa',
      'Gahombo',
      'Gatara',
      'Kabarore',
      'Kayanza',
      'Matongo',
      'Muhanga',
      'Muruta',
      'Rango',
    ],
    'Kirundo': [
      'Bugabira',
      'Busoni',
      'Bwambarangwe',
      'Gitobe',
      'Kirundo',
      'Ntega',
      'Vumbi',
    ],
    'Makamba': [
      'Kayogoro',
      'Kibago',
      'Mabanda',
      'Makamba',
      'Nyanza-Lac',
      'Vugizo',
    ],
    'Muramvya': ['Bukeye', 'Kiganda', 'Mbuye', 'Muramvya', 'Rutegama'],
    'Muyinga': [
      'Buhinyuza',
      'Butihinda',
      'Gashoho',
      'Gasorwe',
      'Giteranyi',
      'Muyinga',
      'Mwakiro',
    ],
    'Mwaro': [
      'Bisoro',
      'Gisozi',
      'Kayokwe',
      'Mwaro',
      'Ndava',
      'Nyabihanga',
      'Rusaka',
    ],
    'Ngozi': [
      'Busiga',
      'Gashikanwa',
      'Kiremba',
      'Marangara',
      'Mwumba',
      'Ngozi',
      'Nyamurenza',
      'Ruhororo',
      'Tangara',
    ],
    'Rumonge': ['Bugarama', 'Burambi', 'Buyengero', 'Muhuta', 'Rumonge'],
    'Rutana': [
      'Bukemba',
      'Giharo',
      'Gitanga',
      'Mpinga-Kayove',
      'Musongati',
      'Rutana',
    ],
    'Ruyigi': [
      'Bweru',
      'Butaganzwa',
      'Butezi',
      'Gisuru',
      'Kinyinya',
      'Nyabitsinda',
      'Ruyigi',
    ],
  };

  static List<String> communesFor(String? province) =>
      communes[province] ?? const [];
}
